import React from 'react'
import '../Style/Transcript.css'

const data ={
    "SPEAKER_00": [
        
        [   
            7.264687500000001,
            13.052812500000002,
            " Oh wow! I am myself a big fan of Avengers and have watched all the movies. I too wanted to go to the theatre and watch the movie, but I was out of station for a family function.",
            [
                {
                    "label": "POSITIVE",
                    "score": 0.9995368719100952
                }
            ],
            "happy"
        ],
        [   
            7.264687500000001,
            13.052812500000002,
            "That’s the place for our reunion. I called up the college regarding this and they gave us permission to have the reunion there. In fact, some of our professors might also be there. I’ve sent out invitations to them too.",
            [
                {
                    "label": "POSITIVE",
                    "score": 0.9995368719100952
                }
            ],
            "sad"
        ],
        [   
            7.264687500000001,
            13.052812500000002,
            "I am doing good. Yes, four long years after college. I got your contact number from Piyush. You remember him, right?",
            [
                {
                    "label": "POSITIVE",
                    "score": 0.9995368719100952
                }
            ],
            "happy"
        ],
        [   
            7.264687500000001,
            13.052812500000002,
            "The first number in each object represents a start time, the second number represents an end time, and the third element is a string that represents the speaker's text. The fourth element is an array of objects that contain a label and score indicating the sentiment of the speaker's text. The fifth element is an array of numbers that represent the probability distribution over eight categories, presumably generated by a machine learning model.",
            [
                {
                    "label": "POSITIVE",
                    "score": 0.9995368719100952
                }
            ],
            "angry"
        ],

    ]
}
const getEmoji = (emotion) => {
    
    switch (emotion) {
      case 'happy':
        return '😄';
      case 'sad':
        return '😞';
      case 'angry':
        return '😐';
      default:
        return '😐';
    }
  };


    
const data2= data.SPEAKER_00;
console.log(data2)
console.log(data2[0])


function Transcript() {
  return (
    <div>
      {Object.keys(data).map((speaker, index) => (
        <div key={index}>
          <p className="SpeakerName">{speaker}</p>
          <ul>
            {data[speaker].map((item, itemIndex) => (
              <div key={itemIndex}>
                    <div className="d-flex flex-row justify-content-around text-bg-light">
                        <p>Start Time : {item[0]}</p>
                        <p>End Time :{item[1]}</p>                        
                    </div>
                    <div className="transcript-box d-flex flex-row justify-content-around">
                        <h2 className="Emojiie">{getEmoji(item[4])}</h2>
                        <p className="textt align-content-lg-center">{item[2]}</p>
                        <p className="label">{item[3][0].label}</p>
                       
                    </div>
                    
              </div>
            ))}
          </ul>
        </div>
      ))}
    </div>
   
   
    
  )
}

export default Transcript